server:
  port: 82


spring:
  redis:
    host: 127.0.0.1
  #????
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
  #??????
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
